name: Jest coverage comment
on:
  push:
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
            output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            message: ${{ steps.coverage.outputs.report }}