name: Jest coverage comment
on:
  push:
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Run tests
        run: npm run unitTests -- --maxWorkers ${{ steps.cpu-cores.outputs.count }}
        
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-final.json