name: Jest coverage comment
on:
  push:
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: |
          npm test --coverage --maxWorkers=2 --coverageReporters json-summary
      
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main